version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "hyperion"
    volumes:
      - ./var/mysql:/var/lib/mysql
  hyperion:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/src
    ports:
      - 8080:8080
    depends_on:
      - db

